apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-saas
  namespace: baas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc-saas
  template:
    metadata:
      labels:
        app: bc-saas
    spec:
      serviceAccountName: bc-saas
      volumes:
        - name: network-json
          secret:
            secretName: bc-saas-secret
        - name: oidc-server-ca
          secret:
            defaultMode: 420
            items:
              - key: ca.crt
                path: ca.pem
            secretName: oidc-server-root-secret
      containers:
        - name: depository
          image: hyperledgerk8s/bc-saas:6b0ed39
          command:
            - depository
          args:
            - -v=5
            - -profile=/opt/depository/network.json
            - -contract=depository
            - -auth=oidc
            - -cert-template-image=/bc-saas/resource/certificate_template.jpg
            - -cert-template-image-eng=/bc-saas/resource/certificate_template_ENG.jpg
            - -cert-ttf-font=/bc-saas/resource/ttf/SourceHanSansCN-Normal.ttf
          ports:
            - containerPort: 9999
          env:
            - name: OIDC_CA_FILE
              value: "/etc/oidc/oidc-server/ca.pem"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: oidc.client-id
                  name: kube-oidc-proxy-config
            - name: OIDC_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  key: oidc.issuer-url
                  name: kube-oidc-proxy-config
            - name: OIDC_USERNAME_CLAIM
              valueFrom:
                secretKeyRef:
                  key: oidc.username-claim
                  name: kube-oidc-proxy-config
            - name: OIDC_GROUPS_CLAIM
              valueFrom:
                secretKeyRef:
                  key: oidc.group-claim
                  name: kube-oidc-proxy-config
          volumeMounts:
            - name: network-json
              mountPath: /opt/depository
            - mountPath: /etc/oidc/oidc-server
              name: oidc-server-ca
              readOnly: true
